### ISSUE TITLE
Scheduled Appointment, but Learn app is still prompting that is NOT scheduled. 

### ISSUE THREAD

**Issue by smithWEBtek** [learn-co-curriculum/rails-assessment#11]
I have successfully scheduled my review appointment with Corinna, but the app is still prompting me to schedule.    (I've gotten all the expected email confirmations and reminders after successfully scheduling, and I've seen this error for 2 days, so it is persisting. )

My appointment is scheduled for Monday, Feb 13 at 9AM with Corinna. 
Also, that time slot is no longer showing as available in the scheduler, (but is was when I originally scheduled) so that's what makes me think this might be an issue on Learn app not getting updated after a successful appointment being scheduled. 

Screen shot:
<img width="1280" alt="learn-error" src="https://cloud.githubusercontent.com/assets/16054332/22862877/25b6809c-f105-11e6-81ee-266ffa0e0e88.png">

**Comment by PeterBell** [comment]
Hi @smithWEBtek thanks so much for raising this. This is a known issue right now with ScheduleOnce integration. Apologies - it's on the backlog to fix. Going to close the issue only because it is known.
