### ISSUE TITLE
Project is overdue?

### ISSUE THREAD

**Issue by jcpny1** [learn-co-curriculum/rails-assessment#12]
I'm currently working on the Rails Portfolio Project. I've filled in the GitHub Repo field.
Now,
1) when I go to the lesson page, I see a red warning banner that says "Rails Portfolio Project portfolio project is overdue. Please complete it before proceeding. >". This same banner appears on my dashboard page as well. I'm not aware of any due date.
2) when I click on the banner, a new browser tab is created, opening to the same lesson page. Seems unnecessary.
3) the new tab has a red warning banner that says "X You do not have access to this lesson." Seems like an error.

**Comment by jcpny1** [comment]
Issue magically disappeared.

**Comment by drakeltheryuujin** [comment]
Hi there! This request sounds like a bug in the Learn platform. [Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum itself (doesn't work,
throws a Ruby error, etc.)

If Learn is misbehaving, please direct your bug report to bugs@learn.co.

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can, and we will try to discern a proper path to resolution.
