### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by ode-to-the-code** [learn-co-curriculum/rails-assessment#29]
Hi there's a typo here, the sentence refers to the reader as both an individual and a group 

"You won’t be expected to be an expert, but people who will be good to work with."

**Comment by gac2117** [comment]
Also, just for better readability, I think the following instruction should be fixed:

Original text:

> Your forms should correctly display validation errors. a. Your fields should be enclosed within a fields_with_errors class b. Error messages describing the validation failures must be present within the view.

But should be:

> Your forms should correctly display validation errors:
A. Your fields should be enclosed within a field_with_errors class.
B. Error messages describing the validation failures must be present within the view.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
