### ISSUE TITLE
contradictory guidance on domain model

### ISSUE THREAD

**Issue by morgvanny** [learn-co-curriculum/rails-assessment#30]
Early on:
"The goal of the application is to build a Content Management System, whether the content being managed is Blog Posts, Recipes, a Library of Resources, or any domain model that lends itself to these requirements"

But then later:

"Restricted Domains
A Blog App - We used a Blog domain design for a lot of the rails lessons and code-alongs."

We shouldn't mention it as a domain model they could choose to meet project requirements and then further down, restrict them from using it.

I also think there are a lot of different blog apps around that have unique features/approaches and solve problems in different ways (Medium, WordPress, Squarespace, Tumblr) so I think it could be totally fine to allow for blog apps, if someone wants to build something more interesting than the barebones lesson and code-along examples.

#staff

**Comment by drakeltheryuujin** [comment]
Thank you for providing feedback.
We have updated the materials. 💙
