### ISSUE TITLE
Incorrect display of portfolio project error message

### ISSUE THREAD

**Issue by aparkening** [learn-co-curriculum/rails-assessment#31]
I'm seeing a warning on every Learn.co page that my Rails project is overdue, but we've just started the project this week. Can you make this message go away until the project is actually overdue? Many of my cohort are seeing the same message.

Error message that's on every Learn.co page (including the Rails project page):

> Rails Portfolio Project portfolio project is overdue. Please complete it before proceeding.

Thanks!

**Comment by drakeltheryuujin** [comment]
Hi there! This request sounds like a problem with the Learn platform.

Our product team can help you with this. You can reach them at support@learn.co.

[Raising issues on GitHub][raise], like you've done here should happen when
there are problems with the curriculum itself (doesn't work, throws a Ruby
error, etc.)

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can to clarify our error,
and we will try to find a fix.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
