### ISSUE TITLE
Add requirement for 1 fully CRUD-able resource

### ISSUE THREAD

**Issue by aturkewi** [learn-co-curriculum/rails-assessment#6]
@PeterBell @mendelB 

I was just thinking that this might be a good requirement to add to the requirement. I was just thinking I don't usually see people use `destroy` (probably because I don't check for it). Thoughts?

If you two think it's worth adding, I'm can add it into the ReadMe and the spec :)

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.

**Comment by PeterBell** [comment]
Hey @aturkewi I quite like that. If it works for @mendelB I'd say go for it and @ mention me in the PR!

**Comment by PeterBell** [comment]
Wow - this is old, and bigger issues, so gonna close it!
